"use client";
import { useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { getCurrentUser, logout } from "../../lib/auth";
import { addChildProfile, getActiveChildProfileForParent, getChildrenForParent, selectChildProfile, updateChildProfile, type ChildProfile } from "../../lib/learning-events";

export default function ParentPage(){ const router=useRouter(); const [children,setChildren]=useState<ChildProfile[]>([]); const [name,setName]=useState(""); const [rename,setRename]=useState<Record<string,string>>({}); const user=getCurrentUser();
  function refresh(){ if(user) setChildren(getChildrenForParent(user.id)); }
  useEffect(()=>{ if(!user){router.replace("/login"); return;} if(user.role!=="parent"){router.replace("/admin"); return;} refresh();},[router]);
  if(!user) return null; const active=getActiveChildProfileForParent(user.id);
  return <main className="page-shell"><section className="hero compact"><p className="eyebrow">Elternbereich</p><h1>Hallo {user.displayName}</h1><p>{active ? `Aktives Kind: ${active.displayName}` : "Wähle zuerst ein Kindprofil aus."}</p><div className="button-row"><a className="button-link" href="/kind/addition">Plus-Werkstatt starten</a><button className="secondary" onClick={()=>{logout(); router.replace("/login")}}>Abmelden</button></div></section><section className="area-grid">{children.map(child=><article className="area-card" key={child.id}><h2>{child.displayName}</h2><p>{child.currentPoints} Werkelpunkte</p><button onClick={()=>{selectChildProfile(child.id, user.id); refresh();}}>Auswählen</button><form className="task-form" onSubmit={e=>{e.preventDefault(); const next=rename[child.id]?.trim(); if(next){updateChildProfile(child.id,{displayName:next}); setRename({...rename,[child.id]:""}); refresh();}}}><input aria-label={`${child.displayName} umbenennen`} placeholder="Neuer Name" value={rename[child.id]??""} onChange={e=>setRename({...rename,[child.id]:e.target.value})}/><button className="secondary">Umbenennen</button></form></article>)}</section><section className="work-card"><h2>Kind hinzufügen</h2><form className="task-form" onSubmit={e=>{e.preventDefault(); if(name.trim()){addChildProfile(name.trim(), user.id); setName(""); refresh();}}}><input aria-label="Name oder Spitzname" placeholder="Name oder Spitzname" value={name} onChange={e=>setName(e.target.value)}/><button>Kind anlegen</button></form></section></main> }
