"use client";

import { useMemo, useState } from "react";
import { createAdditionTask, getAdditionSteps, getCurrentStepState, isAdditionTaskInScope, shouldTriggerRepair, validateAdditionStep, type AdditionStep, type AdditionTask, type AdditionMode, type WorkedExampleStep } from "@werkelwelt/math-engine";
import { listLearningEvents, recordLearningEvent } from "../../../lib/learning-events";

const columns = ["hundreds", "tens", "ones"] as const;
type Column = typeof columns[number];
const guidedSteps: AdditionStep[] = ["ones_digit", "carry_to_tens", "tens_digit", "carry_to_hundreds", "hundreds_sum", "final_result"];
const practiceFields: Array<[AdditionStep, string]> = [["ones_digit","Einer unten"],["carry_to_tens","Übertrag zu Zehner"],["tens_digit","Zehner unten"],["carry_to_hundreds","Übertrag zu Hunderter"],["hundreds_sum","Hunderter unten"]];
const helpTexts = ["Schau zuerst auf die Einerstelle.", "Wir rechnen von rechts nach links.", "Wenn du 14 Einer hast: Wie viele Einer bleiben unten?", "10 Einer werden zu 1 Zehner. 4 Einer bleiben übrig.", "Ich zeige dir diesen Schritt. Den nächsten machst du wieder."];

export default function AdditionPage() {
  const [left, setLeft] = useState("248");
  const [right, setRight] = useState("176");
  const [task, setTask] = useState<AdditionTask | null>(null);
  const [mode, setMode] = useState<AdditionMode>("worked_example");
  const [message, setMessage] = useState("Gib eine Plusaufgabe ein und wähle deinen Lernweg.");
  function start() { const l=Number(left), r=Number(right); if(!isAdditionTaskInScope(l,r)){setMessage("Diese Aufgabe passt noch nicht: Bitte 0 bis 999 und Ergebnis höchstens 999."); return;} const next=createAdditionTask(l,r); setTask(next); setMessage("Die Felder starten leer. Wir bauen die Lösung Schritt für Schritt auf."); recordLearningEvent({event_type:"task_started",mode,task_left:l,task_right:r}); }
  function chooseMode(nextMode:AdditionMode){ setMode(nextMode); if(task) recordLearningEvent({event_type:"mode_selected",mode:nextMode,task_left:task.left,task_right:task.right}); }
  return <main className="addition-app"><header className="addition-top"><div><p className="eyebrow">Kindbereich</p><h1>Plus-Werkstatt</h1><p>{message}</p></div><form className="task-form" onSubmit={e=>{e.preventDefault();start();}}><input aria-label="Erste Zahl" value={left} onChange={e=>setLeft(e.target.value)} inputMode="numeric"/><span>+</span><input aria-label="Zweite Zahl" value={right} onChange={e=>setRight(e.target.value)} inputMode="numeric"/><button>Aufgabe starten</button></form><ModeSelector mode={mode} onChoose={chooseMode}/></header>{task ? <AdditionWorkspace task={task} mode={mode} setMode={chooseMode} onReset={()=>setTask(null)}/> : <section className="orientation-note">Drehe dein Tablet, dann passt die Plus-Werkstatt besser auf den Bildschirm.</section>}</main>;
}
function ModeSelector({mode,onChoose}:{mode:AdditionMode;onChoose:(m:AdditionMode)=>void}){return <nav className="mode-picker compact-modes"><button className={mode==="worked_example"?"active":""} onClick={()=>onChoose("worked_example")}>Zeig es mir</button><button className={mode==="guided_mode"?"active":""} onClick={()=>onChoose("guided_mode")}>Mach mit mir</button><button className={mode==="practice_mode"?"active":""} onClick={()=>onChoose("practice_mode")}>Ich probiere selbst</button></nav>}
function AdditionWorkspace({task,mode,setMode,onReset}:{task:AdditionTask;mode:AdditionMode;setMode:(m:AdditionMode)=>void;onReset:()=>void}){ const [revealed,setRevealed]=useState<Partial<Record<AdditionStep,string>>>({}); const focus = focusFromRevealed(revealed); return <><section className="addition-grid"><PlaceValueBoard task={task} focus={focus} revealed={revealed}/><WrittenAddition task={task} focus={focus} revealed={revealed}/></section>{mode==="worked_example"&&<WorkedExample task={task} setRevealed={setRevealed} onGuided={()=>setMode("guided_mode")} onReset={onReset}/>} {mode==="guided_mode"&&<GuidedMode task={task} revealed={revealed} setRevealed={setRevealed}/>} {mode==="practice_mode"&&<PracticeMode task={task} setRevealed={setRevealed}/>}</> }
function WrittenAddition({task,focus,revealed}:{task:AdditionTask;focus?:Column|"result";revealed:Partial<Record<AdditionStep,string>>}){ const d=(n:number,c:Column)=>getDigits(n)[c]||""; const val=(s:AdditionStep)=>revealed[s]??""; return <section className="written-addition"><h2>Schriftliche Rechnung</h2><div className="calc-grid">{columns.map(c=><div key={`c-${c}`} className={`carry-cell ${focus===c?"focus":""}`}>{c==="hundreds"?val("carry_to_hundreds"):c==="tens"?val("carry_to_tens"):""}</div>)}{columns.map(c=><div key={`l-${c}`} className={focus===c?"focus":"dim"}>{d(task.left,c)}</div>)}<div className="plus">+</div>{columns.map(c=><div key={`r-${c}`} className={focus===c?"focus":"dim"}>{d(task.right,c)}</div>)}<div className="line" />{columns.map(c=><div key={`o-${c}`} className={`result-cell ${focus===c||focus==="result"?"focus":""}`}>{c==="hundreds"?val("hundreds_sum"):c==="tens"?val("tens_digit"):val("ones_digit")}</div>)}</div></section>}
function PlaceValueBoard({task,focus,revealed}:{task:AdditionTask;focus?:Column|"result";revealed:Partial<Record<AdditionStep,string>>}){ return <section className="place-board"><h2>Stellenwerttafel</h2><div className="columns">{columns.map(c=><div className={`place-column ${focus===c?"focus":"dim"}`} key={c}><h3>{c==="hundreds"?"Hunderter":c==="tens"?"Zehner":"Einer"}</h3><Material count={task.leftDigits[c]} kind={c}/><Material count={task.rightDigits[c]} kind={c}/>{c==="ones"&&revealed.carry_to_tens&&<p className="bundle">10 Einer → 1 Zehner, {task.resultDigits.ones} bleiben.</p>}{c==="tens"&&revealed.carry_to_hundreds&&<p className="bundle">10 Zehner → 1 Hunderter, {task.resultDigits.tens} bleiben.</p>}</div>)}</div></section>}
function WorkedExample({task,setRevealed,onGuided,onReset}:{task:AdditionTask;setRevealed:(r:Partial<Record<AdditionStep,string>>)=>void;onGuided:()=>void;onReset:()=>void}){ const steps=useMemo(()=>getAdditionSteps(task),[task]); const [idx,setIdx]=useState(0); const step=steps[idx]!; function next(){ recordLearningEvent({event_type:"worked_example_step_viewed",mode:"worked_example",...(step.step ? { step: step.step } : {}),task_left:task.left,task_right:task.right}); const state=getCurrentStepState(task,idx+1); setRevealed(state.revealed); if(idx<steps.length-1)setIdx(idx+1); else recordLearningEvent({event_type:"worked_example_completed",mode:"worked_example",task_left:task.left,task_right:task.right}); } return <StepInstructionPanel title={step.title} text={step.text}><button onClick={next}>{idx<steps.length-1?"Weiter":"Fertig anzeigen"}</button>{idx===steps.length-1&&<><button onClick={onGuided}>Mach mit mir</button><button className="secondary" onClick={onReset}>Neue Aufgabe</button></>}</StepInstructionPanel> }
function GuidedMode({task,revealed,setRevealed}:{task:AdditionTask;revealed:Partial<Record<AdditionStep,string>>;setRevealed:(r:Partial<Record<AdditionStep,string>>)=>void}){ const active=guidedSteps.filter(s=>!(s==="carry_to_tens"&&task.carries.toTens===0)&&!(s==="carry_to_hundreds"&&task.carries.toHundreds===0)); const [idx,setIdx]=useState(0),[feedback,setFeedback]=useState(""),[help,setHelp]=useState(0),[repair,setRepair]=useState(false); const step=active[idx]!; function pick(v:number){const res=validateAdditionStep(task,step,v); recordLearningEvent({event_type:res.correct?res.successEvent??"correct_partial_step":"incorrect_partial_step",mode:"guided_mode",step,task_left:task.left,task_right:task.right,expected_value:res.expectedValue,actual_value:res.actualValue}); setFeedback(res.feedback); if(res.correct){setRevealed({...revealed,[step]:String(v)}); if(idx<active.length-1)setIdx(idx+1);} else if(shouldTriggerRepair(listLearningEvents(),step)) setRepair(true);} function tip(){const level=Math.min(help+1,5); setHelp(level); setFeedback(helpTexts[level-1]!); recordLearningEvent({event_type:"help_requested",mode:"guided_mode",step,task_left:task.left,task_right:task.right,help_level:level});} if(repair) return <Repair task={task} onDone={()=>{setRepair(false);setFeedback("Gut. Jetzt zurück zu deiner Aufgabe.");}}/>; return <StepInstructionPanel title="Mach mit mir" text={questionFor(task,step)} feedback={feedback}><DigitPicker carry={step.startsWith("carry")} onPick={pick}/><button className="secondary" onClick={tip}>Tipp</button></StepInstructionPanel>}
function PracticeMode({task,setRevealed}:{task:AdditionTask;setRevealed:(r:Partial<Record<AdditionStep,string>>)=>void}){ const [values,setValues]=useState<Partial<Record<AdditionStep,string>>>({}),[feedback,setFeedback]=useState<string[]>([]),[active,setActive]=useState<AdditionStep>("ones_digit"),[help,setHelp]=useState(0); function check(){const notes:string[]=[]; const reveal:Partial<Record<AdditionStep,string>>={}; for(const [step] of practiceFields){const res=validateAdditionStep(task,step,values[step]??""); recordLearningEvent({event_type:res.correct?"correct_partial_step":"incorrect_partial_step",mode:"practice_mode",step,task_left:task.left,task_right:task.right,expected_value:res.expectedValue,actual_value:res.actualValue}); notes.push(res.feedback); if(res.correct) reveal[step]=String(res.expectedValue);} setFeedback(notes); setRevealed(reveal); recordLearningEvent({event_type:"practice_checked",mode:"practice_mode",task_left:task.left,task_right:task.right});} function tip(){const level=Math.min(help+1,5); setHelp(level); setFeedback([helpTexts[level-1]!]); recordLearningEvent({event_type:"help_requested",mode:"practice_mode",step:active,task_left:task.left,task_right:task.right,help_level:level});} return <StepInstructionPanel title="Ich probiere selbst" text="Fülle die Stellen und Überträge aus. Prüfe danach in Ruhe." feedback={feedback.join(" ")}><div className="practice-grid">{practiceFields.map(([s,l])=><label key={s}>{l}<DigitPicker carry={s.startsWith("carry")} onPick={v=>{setActive(s);setValues({...values,[s]:String(v)});}}/><b>{values[s]??"_"}</b></label>)}</div><button onClick={check}>Prüfen</button><button className="secondary" onClick={tip}>Tipp</button></StepInstructionPanel>}
function StepInstructionPanel({title,text,feedback,children}:{title:string;text:string;feedback?:string;children:React.ReactNode}){return <footer className="step-panel"><div><h2>{title}</h2><p>{text}</p>{feedback&&<p className="gentle-note">{feedback}</p>}</div><div className="button-row">{children}</div></footer>}
function DigitPicker({carry,onPick}:{carry?:boolean;onPick:(v:number)=>void}){return <div className="digit-picker">{Array.from({length:carry?2:10},(_,i)=><button key={i} onClick={()=>onPick(i)}>{i}</button>)}</div>}
function Repair({task,onDone}:{task:AdditionTask;onDone:()=>void}){const [idx,setIdx]=useState(0); const items=[13,14,15]; function next(){recordLearningEvent({event_type:idx===0?"repair_started":"repair_step_completed",mode:"guided_mode",repair_type:"bundling_ones_to_tens",task_left:task.left,task_right:task.right}); if(idx>=2)onDone(); else setIdx(idx+1);} return <StepInstructionPanel title="Bündel-Werkzeug" text={`Wir holen kurz das Bündel-Werkzeug. ${items[idx]} Einer sind 1 Zehner und ${items[idx]!%10} Einer.`}><button onClick={next}>Weiter</button></StepInstructionPanel>}
function Material({count,kind}:{count:number;kind:Column}){return <div className="material">{Array.from({length:Math.min(count,12)},(_,i)=><span key={i} className={kind==="ones"?"chip":kind==="tens"?"rod":"plate"}/>)}</div>}
function getDigits(n:number):Record<Column,string>{return {hundreds:Math.floor(n/100)?String(Math.floor(n/100)):"",tens:String(Math.floor((n%100)/10)),ones:String(n%10)}}
function focusFromRevealed(r:Partial<Record<AdditionStep,string>>):Column|"result"{if(!r.ones_digit||!r.carry_to_tens)return "ones"; if(!r.tens_digit||!r.carry_to_hundreds)return "tens"; if(!r.hundreds_sum)return "hundreds"; return "result";}
function questionFor(task:AdditionTask, step:AdditionStep){const q:Record<AdditionStep,string>={ones_sum:`${task.leftDigits.ones} Einer plus ${task.rightDigits.ones} Einer sind ${task.columnSums.ones}.`,ones_digit:`${task.columnSums.ones} Einer: Welche Ziffer kommt unten in die Einerstelle?`,carry_to_tens:"Welcher Übertrag kommt zu den Zehnern?",tens_sum:`Jetzt die Zehner: ${task.leftDigits.tens} + ${task.rightDigits.tens} + ${task.carries.toTens}.`,tens_digit:`${task.columnSums.tensIncludingCarry} Zehner: Welche Ziffer kommt unten?`,carry_to_hundreds:"Welcher Übertrag kommt zu den Hundertern?",hundreds_sum:`Jetzt die Hunderter: ${task.leftDigits.hundreds} plus ${task.rightDigits.hundreds} plus ${task.carries.toHundreds}.`,final_result:"Wie heißt das ganze Ergebnis?"}; return q[step];}
