"use client";

import { useMemo, useState } from "react";
import { createAdditionTask, getActiveColumn, getAdditionBuildSteps, getCurrentStepState, getVisiblePlaceValueState, getVisibleWrittenAdditionState, isAdditionTaskInScope, shouldTriggerRepair, validateAdditionStep, type AdditionColumn, type AdditionMode, type AdditionStep, type AdditionTask } from "@werkelwelt/math-engine";
import { listLearningEvents, recordLearningEvent } from "../../../lib/learning-events";

const columns = ["hundreds", "tens", "ones"] as const;
type Column = AdditionColumn;
const labels: Record<Column, string> = { hundreds: "H", tens: "Z", ones: "E" };
const guidedSteps: AdditionStep[] = ["ones_digit", "carry_to_tens", "tens_digit", "carry_to_hundreds", "hundreds_sum", "final_result"];
const practiceFields: Array<[AdditionStep, string]> = [["ones_digit","Einer unten"],["carry_to_tens","Übertrag zu Zehner"],["tens_digit","Zehner unten"],["carry_to_hundreds","Übertrag zu Hunderter"],["hundreds_sum","Hunderter unten"]];
const helpTexts = ["Schau zuerst auf die Einerstelle.", "Wir rechnen von rechts nach links.", "Wenn du 14 Einer hast: Wie viele Einer bleiben unten?", "10 Einer werden zu 1 Zehner. 4 Einer bleiben übrig.", "Ich zeige dir diesen Schritt. Den nächsten machst du wieder."];

export default function AdditionPage() {
  const [left, setLeft] = useState("16");
  const [right, setRight] = useState("25");
  const [task, setTask] = useState<AdditionTask | null>(null);
  const [mode, setMode] = useState<AdditionMode>("worked_example");
  const [message, setMessage] = useState("Gib eine Plusaufgabe ein und wähle deinen Lernweg.");
  function start() { const l=Number(left), r=Number(right); if(!isAdditionTaskInScope(l,r)){setMessage("Diese Aufgabe passt noch nicht: Bitte 0 bis 999 und Ergebnis höchstens 999."); return;} const next=createAdditionTask(l,r); setTask(next); setMode("worked_example"); setMessage(`${l} + ${r}`); recordLearningEvent({event_type:"task_started",mode,task_left:l,task_right:r}); }
  function suggest(){ const examples=[[16,25],[48,27],[248,176],[395,287]]; const [l,r]=examples[Math.floor(Math.random()*examples.length)]!; setLeft(String(l)); setRight(String(r)); }
  function chooseMode(nextMode:AdditionMode){ setMode(nextMode); if(task) recordLearningEvent({event_type:"mode_selected",mode:nextMode,task_left:task.left,task_right:task.right}); }
  return <main className="addition-app"><header className="addition-top"><div className="addition-title"><p className="eyebrow">Kindbereich</p><h1>Plus-Werkstatt</h1><p>{message}</p></div><AdditionTaskInput left={left} right={right} setLeft={setLeft} setRight={setRight} onStart={start} onSuggest={suggest}/>{task&&<ModeSelector mode={mode} onChoose={chooseMode}/>}</header>{task ? <AdditionWorkspace key={`${task.left}-${task.right}-${mode}`} task={task} mode={mode} setMode={chooseMode} onReset={()=>setTask(null)}/> : <section className="orientation-note">Drehe dein Tablet, dann passt die Plus-Werkstatt besser auf den Bildschirm.</section>}</main>;
}
function AdditionTaskInput({left,right,setLeft,setRight,onStart,onSuggest}:{left:string;right:string;setLeft:(v:string)=>void;setRight:(v:string)=>void;onStart:()=>void;onSuggest:()=>void}){return <form className="task-form" onSubmit={e=>{e.preventDefault();onStart();}}><input aria-label="Erste Zahl" value={left} onChange={e=>setLeft(e.target.value)} inputMode="numeric"/><span className="input-plus">+</span><input aria-label="Zweite Zahl" value={right} onChange={e=>setRight(e.target.value)} inputMode="numeric"/><button>Aufgabe starten</button><button type="button" className="secondary" onClick={onSuggest}>Aufgabe vorschlagen</button></form>}
function ModeSelector({mode,onChoose}:{mode:AdditionMode;onChoose:(m:AdditionMode)=>void}){return <nav className="mode-picker compact-modes"><button className={mode==="worked_example"?"active":""} onClick={()=>onChoose("worked_example")}>Zeig es mir</button><button className={mode==="guided_mode"?"active":""} onClick={()=>onChoose("guided_mode")}>Mach mit mir</button><button className={mode==="practice_mode"?"active":""} onClick={()=>onChoose("practice_mode")}>Ich probiere selbst</button></nav>}
function AdditionWorkspace({task,mode,setMode,onReset}:{task:AdditionTask;mode:AdditionMode;setMode:(m:AdditionMode)=>void;onReset:()=>void}){ const [stepIndex,setStepIndex]=useState(0); const [revealed,setRevealed]=useState<Partial<Record<AdditionStep,string>>>({}); const active=getActiveColumn(task,stepIndex); return <><section className="addition-grid"><PlaceValueBoard task={task} stepIndex={stepIndex} active={active}/><WrittenAdditionGrid task={task} stepIndex={stepIndex} active={active}/></section>{mode==="worked_example"&&<WorkedExample task={task} stepIndex={stepIndex} setStepIndex={setStepIndex} setRevealed={setRevealed} onGuided={()=>setMode("guided_mode")} onReset={onReset}/>} {mode==="guided_mode"&&<GuidedMode task={task} revealed={revealed} setRevealed={setRevealed}/>} {mode==="practice_mode"&&<PracticeMode task={task} setRevealed={setRevealed}/>}</> }
function WrittenAdditionGrid({task,stepIndex,active}:{task:AdditionTask;stepIndex:number;active:Column|"result"|undefined}){ const state=getVisibleWrittenAdditionState(task,stepIndex); const digit=(n:number,c:Column)=>displayDigit(getDigit(n,c), c==="hundreds" ? 100 : c==="tens" ? 10 : 1, n); const result=(c:Column)=>displayResultDigit(state.result[c]??"", c, task.result); return <section className="written-addition"><h2>Schriftliche Rechnung</h2><div className="written-grid" aria-label="Schriftliche Addition"><div className="op-cell" />{columns.map(c=><DigitCell key={`h-${c}`} small className="head-cell" value={labels[c]}/>) }<div className="op-cell carry-label">ü</div>{columns.map(c=><DigitCell key={`c-${c}`} small carry active={active===c} value={c==="hundreds"?state.carries.hundreds??"":c==="tens"?state.carries.tens??"":""}/>) }<div className="op-cell" />{columns.map(c=><DigitCell key={`l-${c}`} tone="first" active={active===c} muted={!!active&&active!==c&&active!=="result"} value={state.showLeft?digit(task.left,c):""}/>) }<div className="op-cell plus">+</div>{columns.map(c=><DigitCell key={`r-${c}`} tone="second" active={active===c} muted={!!active&&active!==c&&active!=="result"} value={state.showRight?digit(task.right,c):""}/>) }<div className="calc-line" /> <div className="op-cell" />{columns.map(c=><DigitCell key={`o-${c}`} result active={active===c||active==="result"} value={result(c)} placeholder={!result(c)}/>)}</div></section>}
function DigitCell({value,active,muted,small,carry,result,placeholder,tone,className=""}:{value:string;active?:boolean;muted?:boolean;small?:boolean;carry?:boolean;result?:boolean;placeholder?:boolean;tone?:"first"|"second";className?:string}){return <div className={`digit-cell ${small?"small":""} ${carry?"carry":""} ${result?"result":""} ${placeholder?"placeholder":""} ${active?"focus":""} ${muted?"dim":""} ${tone?`tone-${tone}`:""} ${className}`}>{placeholder?"□":value}</div>}
function PlaceValueBoard({task,stepIndex,active}:{task:AdditionTask;stepIndex:number;active:Column|"result"|undefined}){ const state=getVisiblePlaceValueState(task,stepIndex); return <section className="place-board"><h2>Stellenwerttafel</h2><div className="columns">{columns.map(c=><PlaceValueColumn key={c} column={c} task={task} state={state} active={active===c}/>)}</div></section>}
function PlaceValueColumn({column,task,state,active}:{column:Column;task:AdditionTask;state:ReturnType<typeof getVisiblePlaceValueState>;active:boolean}){return <div className={`place-column ${active?"focus":""} ${!active?"soft-dim":""}`}><h3>{column==="hundreds"?"Hunderter":column==="tens"?"Zehner":"Einer"}</h3>{state.showLeft&&<Material count={task.leftDigits[column]} kind={column} owner="first" highlight={active}/>} {state.showRight&&<Material count={task.rightDigits[column]} kind={column} owner="second" highlight={active}/>} {column==="ones"&&state.highlightBundledOnes&&<p className="bundle">10 Einer werden gebündelt. {task.resultDigits.ones} bleibt.</p>} {column==="tens"&&state.showCarryToTens&&<CarryBadge label="+ 1 Übertrag"/>} {column==="tens"&&state.highlightBundledTens&&<p className="bundle">10 Zehner werden gebündelt. {task.resultDigits.tens} bleiben.</p>} {column==="hundreds"&&state.showCarryToHundreds&&<CarryBadge label="+ 1 Übertrag"/>}</div>}
function CarryBadge({label}:{label:string}){return <strong className="carry-badge">{label}</strong>}
function WorkedExample({task,stepIndex,setStepIndex,setRevealed,onGuided,onReset}:{task:AdditionTask;stepIndex:number;setStepIndex:(i:number)=>void;setRevealed:(r:Partial<Record<AdditionStep,string>>)=>void;onGuided:()=>void;onReset:()=>void}){ const steps=useMemo(()=>getAdditionBuildSteps(task),[task]); const step=steps[stepIndex]!; const done=stepIndex>=steps.length-1; function next(){ recordLearningEvent({event_type:done?"worked_example_completed":"worked_example_step_viewed",mode:"worked_example",...(step.step ? { step: step.step } : {}),task_left:task.left,task_right:task.right}); const nextIndex=Math.min(stepIndex+1,steps.length-1); setStepIndex(nextIndex); setRevealed(getCurrentStepState(task,nextIndex).revealed); } function restart(){setStepIndex(0); setRevealed({});} return <StepInstructionPanel title={step.title} text={step.text}>{!done&&<button onClick={next}>Weiter</button>}{done&&<><button onClick={restart}>Nochmal zeigen</button><button onClick={onGuided}>Mach mit mir</button><button className="secondary" onClick={onReset}>Neue Aufgabe</button></>}</StepInstructionPanel> }
function GuidedMode({task,revealed,setRevealed}:{task:AdditionTask;revealed:Partial<Record<AdditionStep,string>>;setRevealed:(r:Partial<Record<AdditionStep,string>>)=>void}){ const active=guidedSteps.filter(s=>!(s==="carry_to_tens"&&task.carries.toTens===0)&&!(s==="carry_to_hundreds"&&task.carries.toHundreds===0)); const [idx,setIdx]=useState(0),[feedback,setFeedback]=useState(""),[help,setHelp]=useState(0),[repair,setRepair]=useState(false); const step=active[idx]!; function pick(v:number){const res=validateAdditionStep(task,step,v); recordLearningEvent({event_type:res.correct?res.successEvent??"correct_partial_step":"incorrect_partial_step",mode:"guided_mode",step,task_left:task.left,task_right:task.right,expected_value:res.expectedValue,actual_value:res.actualValue}); setFeedback(res.feedback); if(res.correct){setRevealed({...revealed,[step]:String(v)}); if(idx<active.length-1)setIdx(idx+1);} else if(shouldTriggerRepair(listLearningEvents(),step)) setRepair(true);} function tip(){const level=Math.min(help+1,5); setHelp(level); setFeedback(helpTexts[level-1]!); recordLearningEvent({event_type:"help_requested",mode:"guided_mode",step,task_left:task.left,task_right:task.right,help_level:level});} if(repair) return <Repair task={task} onDone={()=>{setRepair(false);setFeedback("Gut. Jetzt zurück zu deiner Aufgabe.");}}/>; return <StepInstructionPanel title="Mach mit mir" text={questionFor(task,step)} feedback={feedback}><DigitPicker carry={step.startsWith("carry")} onPick={pick}/><button className="secondary" onClick={tip}>Tipp</button></StepInstructionPanel>}
function PracticeMode({task,setRevealed}:{task:AdditionTask;setRevealed:(r:Partial<Record<AdditionStep,string>>)=>void}){ const [values,setValues]=useState<Partial<Record<AdditionStep,string>>>({}),[feedback,setFeedback]=useState<string[]>([]),[active,setActive]=useState<AdditionStep>("ones_digit"),[help,setHelp]=useState(0); function check(){const notes:string[]=[]; const reveal:Partial<Record<AdditionStep,string>>={}; for(const [step] of practiceFields){const res=validateAdditionStep(task,step,values[step]??""); recordLearningEvent({event_type:res.correct?"correct_partial_step":"incorrect_partial_step",mode:"practice_mode",step,task_left:task.left,task_right:task.right,expected_value:res.expectedValue,actual_value:res.actualValue}); notes.push(res.feedback); if(res.correct) reveal[step]=String(res.expectedValue);} setFeedback(notes); setRevealed(reveal); recordLearningEvent({event_type:"practice_checked",mode:"practice_mode",task_left:task.left,task_right:task.right});} function tip(){const level=Math.min(help+1,5); setHelp(level); setFeedback([helpTexts[level-1]!]); recordLearningEvent({event_type:"help_requested",mode:"practice_mode",step:active,task_left:task.left,task_right:task.right,help_level:level});} return <StepInstructionPanel title="Ich probiere selbst" text="Fülle die Stellen und Überträge aus. Prüfe danach in Ruhe." feedback={feedback.join(" ")}><div className="practice-grid">{practiceFields.map(([s,l])=><label key={s}>{l}<DigitPicker carry={s.startsWith("carry")} onPick={v=>{setActive(s);setValues({...values,[s]:String(v)});}}/><b>{values[s]??"_"}</b></label>)}</div><button onClick={check}>Prüfen</button><button className="secondary" onClick={tip}>Tipp</button></StepInstructionPanel>}
function StepInstructionPanel({title,text,feedback,children}:{title:string;text:string;feedback?:string;children:React.ReactNode}){return <footer className="step-panel"><div><h2>{title}</h2><p>{text}</p>{feedback&&<p className="gentle-note">{feedback}</p>}</div><div className="button-row">{children}</div></footer>}
function DigitPicker({carry,onPick}:{carry?:boolean;onPick:(v:number)=>void}){return <div className="digit-picker">{Array.from({length:carry?2:10},(_,i)=><button key={i} onClick={()=>onPick(i)}>{i}</button>)}</div>}
function Repair({task,onDone}:{task:AdditionTask;onDone:()=>void}){const [idx,setIdx]=useState(0); const items=[13,14,15]; function next(){recordLearningEvent({event_type:idx===0?"repair_started":"repair_step_completed",mode:"guided_mode",repair_type:"bundling_ones_to_tens",task_left:task.left,task_right:task.right}); if(idx>=2)onDone(); else setIdx(idx+1);} return <StepInstructionPanel title="Bündel-Werkzeug" text={`Wir holen kurz das Bündel-Werkzeug. ${items[idx]} Einer sind 1 Zehner und ${items[idx]!%10} Einer.`}><button onClick={next}>Weiter</button></StepInstructionPanel>}
function Material({count,kind,owner,highlight}:{count:number;kind:Column;owner:"first"|"second";highlight?:boolean}){return <div className={`material ${owner} ${highlight?"material-focus":""}`}>{Array.from({length:Math.min(count,12)},(_,i)=><span key={i} className={`${kind==="ones"?"chip":kind==="tens"?"rod":"plate"} ${i<10&&highlight?"counted":""}`}/>)}</div>}
function getDigit(n:number,c:Column){return c==="hundreds"?Math.floor(n/100):c==="tens"?Math.floor((n%100)/10):n%10}
function displayDigit(value:number, place:number, full:number){return full<place ? "" : String(value)}
function displayResultDigit(value:string, column:Column, result:number){return column==="hundreds"&&result<100 ? "" : value}
function questionFor(task:AdditionTask, step:AdditionStep){const q:Record<AdditionStep,string>={ones_sum:`${task.leftDigits.ones} Einer plus ${task.rightDigits.ones} Einer sind ${task.columnSums.ones}.`,ones_digit:`${task.columnSums.ones} Einer: Welche Ziffer kommt unten in die Einerstelle?`,carry_to_tens:"Welcher Übertrag kommt zu den Zehnern?",tens_sum:`Jetzt die Zehner: ${task.leftDigits.tens} + ${task.rightDigits.tens} + ${task.carries.toTens}.`,tens_digit:`${task.columnSums.tensIncludingCarry} Zehner: Welche Ziffer kommt unten?`,carry_to_hundreds:"Welcher Übertrag kommt zu den Hundertern?",hundreds_sum:`Jetzt die Hunderter: ${task.leftDigits.hundreds} plus ${task.rightDigits.hundreds} plus ${task.carries.toHundreds}.`,final_result:"Wie heißt das ganze Ergebnis?"}; return q[step];}
