"use client";

import { useEffect, useMemo, useState } from "react";
import { analyzeAdditionTask, createAdditionTask, generateAdditionSuggestion, getActiveColumnForMode, getAdditionBuildSteps, getCurrentStepState, getVisibleColumns, getVisiblePlaceValueStateForMode, getVisibleWrittenAdditionStateForMode, isAdditionTaskInScope, shouldTriggerRepair, suggestNextAdditionTask, validateAdditionStep, type AdditionColumn, type AdditionMode, type AdditionStep, type AdditionTask } from "@werkelwelt/math-engine";
import { listLearningEvents, recordLearningEvent } from "../../../lib/learning-events";

type Column = AdditionColumn;
const labels: Record<Column, string> = { millions: "M", hundred_thousands: "HT", ten_thousands: "ZT", thousands: "T", hundreds: "H", tens: "Z", ones: "E" };
const guidedSteps: AdditionStep[] = ["ones_digit", "carry_to_tens", "tens_digit", "carry_to_hundreds", "hundreds_sum", "final_result"];
const practiceFields: Array<[AdditionStep, string]> = [["ones_digit","Einer unten"],["carry_to_tens","Übertrag zu Zehner"],["tens_digit","Zehner unten"],["carry_to_hundreds","Übertrag zu Hunderter"],["hundreds_sum","Hunderter unten"]];
const helpTexts = ["Schau zuerst auf die Einerstelle.", "Wir rechnen von rechts nach links.", "Wenn du 14 Einer hast: Wie viele Einer bleiben unten?", "10 Einer werden zu 1 Zehner. 4 Einer bleiben übrig.", "Ich zeige dir diesen Schritt. Den nächsten machst du wieder."];

export default function AdditionPage() {
  const [left, setLeft] = useState("16");
  const [right, setRight] = useState("25");
  const [task, setTask] = useState<AdditionTask | null>(null);
  const [mode, setMode] = useState<AdditionMode>("worked_example");
  const [message, setMessage] = useState("Gib eine Plusaufgabe ein und wähle deinen Lernweg.");
  function start() { const l=Number(left), r=Number(right); if(!isAdditionTaskInScope(l,r)){setMessage("Diese Aufgabe passt noch nicht: Bitte 0 bis 1.000.000 und Ergebnis höchstens 1.000.000."); return;} const next=createAdditionTask(l,r); setTask(next); setMode("worked_example"); setMessage(`${l} + ${r}`); recordLearningEvent({event_type:"task_started",mode,task_left:l,task_right:r,difficulty_class:analyzeAdditionTask(l,r).difficultyClass}); }
  function suggest(){ const events=listLearningEvents(); const recent=events.filter(e=>e.task_left!==undefined&&e.task_right!==undefined).map(e=>({left:e.task_left!,right:e.task_right!})); const suggestion=suggestNextAdditionTask([], events, {avoidRecentTasks:recent}); setLeft(String(suggestion.left)); setRight(String(suggestion.right)); setMessage(`Vorschlag: ${suggestion.left} + ${suggestion.right}`); }
  function chooseMode(nextMode:AdditionMode){ setMode(nextMode); if(task) recordLearningEvent({event_type:"mode_selected",mode:nextMode,task_left:task.left,task_right:task.right}); }
  return <main className="addition-app"><header className="addition-top"><div className="addition-title"><p className="eyebrow">Kindbereich</p><h1>Plus-Werkstatt</h1><p>{message}</p></div><AdditionTaskInput left={left} right={right} setLeft={setLeft} setRight={setRight} onStart={start} onSuggest={suggest}/>{task&&<ModeSelector mode={mode} onChoose={chooseMode}/>}</header>{task ? <AdditionWorkspace key={`${task.left}-${task.right}`} task={task} mode={mode} setMode={chooseMode} onReset={()=>setTask(null)}/> : <section className="orientation-note">Drehe dein Tablet, dann passt die Plus-Werkstatt besser auf den Bildschirm.</section>}</main>;
}
function AdditionTaskInput({left,right,setLeft,setRight,onStart,onSuggest}:{left:string;right:string;setLeft:(v:string)=>void;setRight:(v:string)=>void;onStart:()=>void;onSuggest:()=>void}){return <form className="task-form" onSubmit={e=>{e.preventDefault();onStart();}}><input aria-label="Erste Zahl" value={left} onChange={e=>setLeft(e.target.value)} inputMode="numeric"/><span className="input-plus">+</span><input aria-label="Zweite Zahl" value={right} onChange={e=>setRight(e.target.value)} inputMode="numeric"/><button>Aufgabe starten</button><button type="button" className="secondary" onClick={onSuggest}>Aufgabe vorschlagen</button></form>}
function ModeSelector({mode,onChoose}:{mode:AdditionMode;onChoose:(m:AdditionMode)=>void}){return <nav className="mode-picker compact-modes"><button className={mode==="worked_example"?"active":""} onClick={()=>onChoose("worked_example")}>Zeig es mir</button><button className={mode==="guided_mode"?"active":""} onClick={()=>onChoose("guided_mode")}>Mach mit mir</button><button className={mode==="practice_mode"?"active":""} onClick={()=>onChoose("practice_mode")}>Ich probiere selbst</button></nav>}
function AdditionWorkspace({task,mode,setMode,onReset}:{task:AdditionTask;mode:AdditionMode;setMode:(m:AdditionMode)=>void;onReset:()=>void}){ const [stepIndex,setStepIndex]=useState(0); const [guidedIndex,setGuidedIndex]=useState(0); const [revealed,setRevealed]=useState<Partial<Record<AdditionStep,string>>>({}); const [practiceActive,setPracticeActive]=useState<AdditionStep>("ones_digit"); const guidedActiveSteps=visibleGuidedSteps(task); const activeStep=mode==="guided_mode"?guidedActiveSteps[guidedIndex]:mode==="practice_mode"?practiceActive:undefined; const active=mode==="guided_mode"?columnForUiStep(guidedActiveSteps[guidedIndex]):getActiveColumnForMode(task,mode,stepIndex,practiceActive); return <><section className="addition-grid"><PlaceValueBoard task={task} mode={mode} stepIndex={stepIndex} active={active}/><WrittenAdditionGrid task={task} mode={mode} stepIndex={stepIndex} active={active} activeStep={activeStep} revealed={revealed}/></section><MoodQuestion task={task}/>{mode==="worked_example"&&<WorkedExample task={task} stepIndex={stepIndex} setStepIndex={setStepIndex} setRevealed={setRevealed} onGuided={()=>setMode("guided_mode")} onReset={onReset}/>} {mode==="guided_mode"&&<GuidedMode task={task} revealed={revealed} setRevealed={setRevealed} idx={guidedIndex} setIdx={setGuidedIndex}/>} {mode==="practice_mode"&&<PracticeMode task={task} setRevealed={setRevealed} active={practiceActive} setActive={setPracticeActive}/>}</> }
function WrittenAdditionGrid({task,mode,stepIndex,active,activeStep,revealed}:{task:AdditionTask;mode:AdditionMode;stepIndex:number;active:Column|"result"|undefined;activeStep:AdditionStep|undefined;revealed:Partial<Record<AdditionStep,string>>}){ const state=getVisibleWrittenAdditionStateForMode(task,mode,stepIndex,revealed); const columns=state.columns; const digit=(n:number,c:Column)=>displayDigit(getDigit(n,c), placeValue(c), n); const result=(c:Column)=>state.result[c]??""; return <section className="written-addition"><h2>Schriftliche Rechnung</h2><div className="written-grid" style={{gridTemplateColumns:`2rem repeat(${columns.length}, minmax(3.2rem, 4.2rem))`}} aria-label="Schriftliche Addition"><div className="op-cell" />{columns.map(c=><DigitCell key={`h-${c}`} small className="head-cell" value={labels[c]}/>) }<div className="op-cell carry-label">ü</div>{columns.map(c=><DigitCell key={`c-${c}`} small carry active={(activeStep==="carry_to_tens"&&c==="tens")||(activeStep==="carry_to_hundreds"&&c==="hundreds")||(!activeStep&&active===c)} value={c==="thousands"?state.carries.thousands??"":c==="hundreds"?state.carries.hundreds??"":c==="tens"?state.carries.tens??"":""}/>) }<div className="op-cell" />{columns.map(c=><DigitCell key={`l-${c}`} tone="first" active={active===c} muted={!!active&&active!==c&&active!=="result"} value={state.showLeft?digit(task.left,c):""}/>) }<div className="op-cell plus">+</div>{columns.map(c=><DigitCell key={`r-${c}`} tone="second" active={active===c} muted={!!active&&active!==c&&active!=="result"} value={state.showRight?digit(task.right,c):""}/>) }<div className="calc-line" /> <div className="op-cell" />{columns.map(c=><DigitCell key={`o-${c}`} result active={(activeStep==="ones_digit"&&c==="ones")||(activeStep==="tens_digit"&&c==="tens")||(activeStep==="hundreds_sum"&&c==="hundreds")||(!activeStep&&(active===c||active==="result"))} value={result(c)} placeholder={!result(c)}/>)}</div></section>}
function DigitCell({value,active,muted,small,carry,result,placeholder,tone,className=""}:{value:string;active?:boolean;muted?:boolean;small?:boolean;carry?:boolean;result?:boolean;placeholder?:boolean;tone?:"first"|"second";className?:string}){return <div className={`digit-cell ${small?"small":""} ${carry?"carry":""} ${result?"result":""} ${placeholder?"placeholder":""} ${active?"focus":""} ${muted?"dim":""} ${tone?`tone-${tone}`:""} ${className}`}>{placeholder?"□":value}</div>}
function PlaceValueBoard({task,mode,stepIndex,active}:{task:AdditionTask;mode:AdditionMode;stepIndex:number;active:Column|"result"|undefined}){ const state=getVisiblePlaceValueStateForMode(task,mode,stepIndex); const columns=getVisibleColumns(task); return <section className="place-board"><h2>Stellenwerttafel</h2><div className="columns" style={{gridTemplateColumns:`repeat(${columns.length}, minmax(0, 1fr))`}}>{columns.map(c=><PlaceValueColumn key={c} column={c} task={task} state={state} active={active===c}/>)}</div></section>}
function PlaceValueColumn({column,task,state,active}:{column:Column;task:AdditionTask;state:ReturnType<typeof getVisiblePlaceValueStateForMode>;active:boolean}){ const bundled=column==="ones"?state.bundledOnes:column==="tens"?state.bundledTens:null; const carried=(column==="tens"&&state.showCarryToTens)||(column==="hundreds"&&state.showCarryToHundreds)||(column==="thousands"&&state.showCarryToThousands); return <div className={`place-column ${active?"focus":""} ${!active?"soft-dim":""}`}><h3>{placeLabel(column)}</h3>{bundled ? <BundledMaterial task={task} column={column} state={bundled}/> : <>{state.showLeft&&<Material count={task.leftDigits[column]} kind={column} owner="first" highlight={active}/>} {state.showRight&&<Material count={task.rightDigits[column]} kind={column} owner="second" highlight={active}/>}</>} {carried&&<CarryBadge label="+ 1 Übertrag"/>} {bundled&&<p className="bundle">10 {placeLabel(column)} werden zu 1 {placeLabel(bundled.to)}. {bundled.remainingCount} bleiben unten.</p>}</div>}
function CarryBadge({label}:{label:string}){return <strong className="carry-badge">{label}</strong>}
function WorkedExample({task,stepIndex,setStepIndex,setRevealed,onGuided,onReset}:{task:AdditionTask;stepIndex:number;setStepIndex:(i:number)=>void;setRevealed:(r:Partial<Record<AdditionStep,string>>)=>void;onGuided:()=>void;onReset:()=>void}){ const steps=useMemo(()=>getAdditionBuildSteps(task),[task]); const step=steps[stepIndex]!; const done=stepIndex>=steps.length-1; function next(){ recordLearningEvent({event_type:done?"worked_example_completed":"worked_example_step_viewed",mode:"worked_example",...(step.step ? { step: step.step } : {}),task_left:task.left,task_right:task.right}); const nextIndex=Math.min(stepIndex+1,steps.length-1); setStepIndex(nextIndex); setRevealed(getCurrentStepState(task,nextIndex).revealed); } function restart(){setStepIndex(0); setRevealed({});} return <StepInstructionPanel title={step.title} text={step.text}>{!done&&<button onClick={next}>Weiter</button>}{done&&<><button onClick={restart}>Nochmal zeigen</button><button onClick={onGuided}>Mach mit mir</button><button className="secondary" onClick={onReset}>Neue Aufgabe</button></>}</StepInstructionPanel> }
function GuidedMode({task,revealed,setRevealed,idx,setIdx}:{task:AdditionTask;revealed:Partial<Record<AdditionStep,string>>;setRevealed:(r:Partial<Record<AdditionStep,string>>)=>void;idx:number;setIdx:(i:number)=>void}){ const active=visibleGuidedSteps(task); const [feedback,setFeedback]=useState(""),[help,setHelp]=useState(0),[repair,setRepair]=useState(false); const step=active[idx]!; function pick(v:number){const res=validateAdditionStep(task,step,v); recordLearningEvent({event_type:res.correct?res.successEvent??"correct_partial_step":"incorrect_partial_step",mode:"guided_mode",step,task_left:task.left,task_right:task.right,expected_value:res.expectedValue,actual_value:res.actualValue}); setFeedback(res.feedback); if(res.correct){setRevealed({...revealed,[step]:String(v)}); if(idx<active.length-1)setIdx(idx+1);} else if(shouldTriggerRepair(listLearningEvents(),step)) setRepair(true);} function tip(){const level=Math.min(help+1,5); setHelp(level); setFeedback(helpTexts[level-1]!); recordLearningEvent({event_type:"help_requested",mode:"guided_mode",step,task_left:task.left,task_right:task.right,help_level:level});} if(repair) return <Repair task={task} onDone={()=>{setRepair(false);setFeedback("Gut. Jetzt zurück zu deiner Aufgabe.");}}/>; return <StepInstructionPanel title="Mach mit mir" text={questionFor(task,step)} feedback={feedback}><DigitPicker carry={step.startsWith("carry")} onPick={pick}/><button className="secondary" onClick={tip}>Tipp</button></StepInstructionPanel>}
function PracticeMode({task,setRevealed,active,setActive}:{task:AdditionTask;setRevealed:(r:Partial<Record<AdditionStep,string>>)=>void;active:AdditionStep;setActive:(s:AdditionStep)=>void}){ const fields=visiblePracticeFields(task); const [values,setValues]=useState<Partial<Record<AdditionStep,string>>>({}),[feedback,setFeedback]=useState<string[]>([]),[help,setHelp]=useState(0); function check(){const notes:string[]=[]; const reveal:Partial<Record<AdditionStep,string>>={}; for(const [step] of fields){const res=validateAdditionStep(task,step,values[step]??""); recordLearningEvent({event_type:res.correct?"correct_partial_step":"incorrect_partial_step",mode:"practice_mode",step,task_left:task.left,task_right:task.right,expected_value:res.expectedValue,actual_value:res.actualValue}); notes.push(res.feedback); if(res.correct) reveal[step]=String(res.expectedValue);} setFeedback(notes); setRevealed(reveal); recordLearningEvent({event_type:"practice_checked",mode:"practice_mode",task_left:task.left,task_right:task.right});} function tip(){const level=Math.min(help+1,5); setHelp(level); setFeedback([helpTexts[level-1]!]); recordLearningEvent({event_type:"help_requested",mode:"practice_mode",step:active,task_left:task.left,task_right:task.right,help_level:level});} function nextAfter(step:AdditionStep){const index=fields.findIndex(([candidate])=>candidate===step); if(index>=0&&index<fields.length-1)setActive(fields[index+1]![0]);}
  function revealValues(next:Partial<Record<AdditionStep,string>>){setRevealed(next);}
  function enter(step:AdditionStep,value:string,advance=true){ if(step.startsWith("carry")&&!/^[01]$/.test(value)){setFeedback(["Hier passt nur 0 oder 1."]); return false;} if(!step.startsWith("carry")&&!/^\d$/.test(value)) return false; const next={...values,[step]:value}; setValues(next); revealValues(next); if(advance)nextAfter(step); return true; }
  function allFieldsFilled(){return fields.every(([step])=>values[step]!==undefined&&values[step]!=="");}
  useEffect(()=>{function onKey(event:KeyboardEvent){ if(event.target instanceof HTMLInputElement) return; const digit=event.key.match(/^\d$/)?.[0] ?? event.code.match(/^Numpad(\d)$/)?.[1]; if(digit){ event.preventDefault(); enter(active,digit,true); return;} if(event.key==="Backspace"){event.preventDefault(); const next={...values,[active]:""}; setValues(next); revealValues(next);} if(event.key==="Enter"){event.preventDefault(); if(allFieldsFilled()) check(); else {const firstEmpty=fields.find(([step])=>!values[step]); if(firstEmpty)setActive(firstEmpty[0]);}}} window.addEventListener("keydown",onKey); return ()=>window.removeEventListener("keydown",onKey);},[active,values,fields]);
  return <StepInstructionPanel title="Ich probiere selbst" text="Fülle die Stellen und Überträge aus. Prüfe danach in Ruhe. Tastatur und Zehnertastatur funktionieren auch." feedback={feedback.join(" ")}><div className="practice-grid">{fields.map(([s,l])=><button type="button" className={`practice-field ${active===s?"active":""}`} key={s} onClick={()=>setActive(s)}>{l}<DigitPicker carry={s.startsWith("carry")} onPick={v=>{setActive(s);enter(s,String(v),true);}}/><b>{values[s]||"_"}</b></button>)}</div><button onClick={check}>Prüfen</button><button className="secondary" onClick={tip}>Tipp</button></StepInstructionPanel>}
function visiblePracticeFields(task:AdditionTask){const visible=getVisibleColumns(task); return practiceFields.filter(([s])=>isPracticeStepVisible(task,visible,s));}
function visibleGuidedSteps(task:AdditionTask){const visible=getVisibleColumns(task); return guidedSteps.filter(s=>isPracticeStepVisible(task,visible,s)||s==="final_result");}
function isPracticeStepVisible(task:AdditionTask,visible:Column[],step:AdditionStep){ if(step==="hundreds_sum")return visible.includes("hundreds"); if(step==="carry_to_tens")return task.carries.toTens>0||(visible.includes("hundreds")&&task.leftDigits.tens>0&&task.rightDigits.tens>0); if(step==="carry_to_hundreds")return task.carries.toHundreds>0||visible.includes("hundreds"); return true;}
function StepInstructionPanel({title,text,feedback,children}:{title:string;text:string;feedback?:string;children:React.ReactNode}){return <footer className="step-panel"><div><h2>{title}</h2><p>{text}</p>{feedback&&<p className="gentle-note">{feedback}</p>}</div><div className="button-row">{children}</div></footer>}
function DigitPicker({carry,onPick}:{carry?:boolean;onPick:(v:number)=>void}){return <div className="digit-picker">{Array.from({length:carry?2:10},(_,i)=><button key={i} onClick={()=>onPick(i)}>{i}</button>)}</div>}
function Repair({task,onDone}:{task:AdditionTask;onDone:()=>void}){const [idx,setIdx]=useState(0); const items=[13,14,15]; function next(){recordLearningEvent({event_type:idx===0?"repair_started":"repair_step_completed",mode:"guided_mode",repair_type:"bundling_ones_to_tens",task_left:task.left,task_right:task.right}); if(idx>=2)onDone(); else setIdx(idx+1);} return <StepInstructionPanel title="Bündel-Werkzeug" text={`Wir holen kurz das Bündel-Werkzeug. ${items[idx]} Einer sind 1 Zehner und ${items[idx]!%10} Einer.`}><button onClick={next}>Weiter</button></StepInstructionPanel>}
function Material({count,kind,owner,highlight}:{count:number;kind:Column;owner:"first"|"second"|"carry";highlight?:boolean}){return <div className={`material ${owner} ${highlight?"material-focus":""}`}>{Array.from({length:Math.min(count,12)},(_,i)=><span key={i} className={`${materialClass(kind)} ${i<10&&highlight?"counted":""}`}/>)}</div>}
function BundledMaterial({task,column,state}:{task:AdditionTask;column:Column;state:{remainingCount:number}}){const total=task.leftDigits[column]+task.rightDigits[column]; return <div className="bundle-material"><div className="bundle-pack" aria-label={`10 ${placeLabel(column)} werden gebündelt`}>{Array.from({length:10},(_,i)=><span key={i} className={`${materialClass(column)} counted fading`}/>)}</div><Material count={Math.max(0,total-10)} kind={column} owner="first"/></div>}
function getDigit(n:number,c:Column){return c==="millions"?Math.floor(n/1000000):c==="hundred_thousands"?Math.floor((n%1000000)/100000):c==="ten_thousands"?Math.floor((n%100000)/10000):c==="thousands"?Math.floor((n%10000)/1000):c==="hundreds"?Math.floor((n%1000)/100):c==="tens"?Math.floor((n%100)/10):n%10}
function placeValue(c:Column){return c==="millions"?1000000:c==="hundred_thousands"?100000:c==="ten_thousands"?10000:c==="thousands"?1000:c==="hundreds"?100:c==="tens"?10:1}
function placeLabel(c:Column){return c==="millions"?"Million":c==="hundred_thousands"?"Hunderttausender":c==="ten_thousands"?"Zehntausender":c==="thousands"?"Tausender":c==="hundreds"?"Hunderter":c==="tens"?"Zehner":"Einer"}
function materialClass(c:Column){return c==="ones"?"chip":c==="tens"?"rod":"plate"}
function displayDigit(value:number, place:number, full:number){return full<place ? "" : String(value)}
function questionFor(task:AdditionTask, step:AdditionStep){const q:Record<AdditionStep,string>={ones_sum:`${task.leftDigits.ones} Einer plus ${task.rightDigits.ones} Einer sind ${task.columnSums.ones}.`,ones_digit:`${task.columnSums.ones} Einer: Welche Ziffer kommt unten in die Einerstelle?`,carry_to_tens:"Welcher Übertrag kommt zu den Zehnern?",tens_sum:`Jetzt die Zehner: ${task.leftDigits.tens} + ${task.rightDigits.tens} + ${task.carries.toTens}.`,tens_digit:`${task.columnSums.tensIncludingCarry} Zehner: Welche Ziffer kommt unten?`,carry_to_hundreds:"Welcher Übertrag kommt zu den Hundertern?",hundreds_sum:`Jetzt die Hunderter: ${task.leftDigits.hundreds} plus ${task.rightDigits.hundreds} plus ${task.carries.toHundreds}.`,final_result:"Wie heißt das ganze Ergebnis?"}; return q[step];}

function MoodQuestion({task}:{task:AdditionTask}){ const [saved,setSaved]=useState<string>(""); function save(mood:"easy"|"ok"|"hard"|"too_much"){ recordLearningEvent({event_type:"session_mood_reported",mode:"practice_mode",task_left:task.left,task_right:task.right,mood,difficulty_class:analyzeAdditionTask(task.left,task.right).difficultyClass}); setSaved(mood); } return <section className="mood-card"><h2>Wie war es heute?</h2><div className="button-row"><button onClick={()=>save("easy")}>🙂 leicht</button><button onClick={()=>save("ok")}>😐 okay</button><button onClick={()=>save("hard")}>🙁 schwer</button><button onClick={()=>save("too_much")}>😣 zu viel</button></div>{saved&&<p className="gentle-note">Gespeichert: {saved}</p>}</section>}

function columnForUiStep(step:AdditionStep|undefined):Column|"result"|undefined{ if(!step)return "ones"; if(step==="ones_digit"||step==="ones_sum")return "ones"; if(step==="carry_to_tens"||step==="tens_digit"||step==="tens_sum")return "tens"; if(step==="carry_to_hundreds"||step==="hundreds_sum")return "hundreds"; return "result";}
