import assert from "node:assert/strict";
import { createAdditionTask, validateAdditionStep, shouldTriggerRepair } from "../src/index.js";

const task = createAdditionTask(48, 27);
assert.equal(task.result, 75);
assert.equal(validateAdditionStep(task, "ones_sum", 15).correct, true);
assert.equal(validateAdditionStep(task, "ones_digit", 5).correct, true);
assert.equal(validateAdditionStep(task, "carry_to_tens", 1).correct, true);
assert.equal(validateAdditionStep(task, "tens_sum", 7).correct, true);
assert.equal(validateAdditionStep(task, "ones_digit", 15).mistake?.type, "wrote_full_ones_sum_in_ones_place");
assert.equal(validateAdditionStep(task, "carry_to_tens", 0).mistake?.type, "missing_carry");
const noCarry = createAdditionTask(23, 14);
assert.equal(noCarry.result, 37);
assert.equal(validateAdditionStep(noCarry, "carry_to_tens", 0).correct, true);
assert.equal(validateAdditionStep(noCarry, "tens_sum", 3).correct, true);
const threeDigit = createAdditionTask(248, 176);
assert.equal(threeDigit.result, 424);
assert.equal(validateAdditionStep(threeDigit, "ones_sum", 14).correct, true);
assert.equal(validateAdditionStep(threeDigit, "carry_to_tens", 1).correct, true);
assert.equal(validateAdditionStep(threeDigit, "tens_sum", 12).correct, true);
assert.equal(validateAdditionStep(threeDigit, "carry_to_hundreds", 1).correct, true);
assert.equal(shouldTriggerRepair([{ event_type: "incorrect_partial_step", step: "ones_digit" }, { event_type: "help_requested", step: "carry_to_tens", help_level: 2 }], "carry_to_tens"), true);
console.log("addition math-engine tests passed");
