"use client";

import { useEffect, useState } from "react";
import type { AdditionLearningEvent } from "@werkelwelt/types";
import { getFamilyState, listLearningEvents, listLearningSessions, listRewardEvents, summarizeLearningEvents, type ChildProfile } from "../../../lib/learning-events";

export default function ParentEventsPage() {
  const [events, setEvents] = useState<AdditionLearningEvent[]>([]);
  const [children, setChildren] = useState<ChildProfile[]>([]);
  const [selectedChildId, setSelectedChildId] = useState<string | undefined>();
  useEffect(() => { const load=()=>{ const family=getFamilyState(); setChildren(family.children); setSelectedChildId((current)=>current ?? family.children[0]?.id); setEvents(listLearningEvents()); }; load(); window.addEventListener("werkelwelt-learning-events", load); window.addEventListener("werkelwelt-family", load); return () => { window.removeEventListener("werkelwelt-learning-events", load); window.removeEventListener("werkelwelt-family", load); }; }, []);
  const child = children.find((item) => item.id === selectedChildId) ?? children[0];
  const childEvents = child ? events.filter((event) => event.child_profile_id === child.id) : [];
  const childRewards = child ? listRewardEvents().filter((reward) => reward.childProfileId === child.id) : [];
  const summary = summarizeLearningEvents(childEvents, childRewards);
  const lastSession = child ? listLearningSessions().filter((session) => session.childProfileId === child.id).sort((a,b)=>String(b.startedAt).localeCompare(String(a.startedAt)))[0] : undefined;
  return <main className="page-shell learning-shell"><section className="hero compact"><p className="eyebrow">Elternbereich</p><h1>Kinder und Fortschritt</h1><p className="subtitle">Lokaler Familienmodus mit Test-Elternkonto. Kindprofile haben keine E-Mail-Adresse.</p></section><section className="area-grid">{children.map((profile)=><button key={profile.id} className="area-card" onClick={()=>setSelectedChildId(profile.id)}><h2>{profile.displayName}</h2><p>{profile.currentPoints} Werkelpunkte</p><p>Letzte Runde: {lastRoundLabel(profile.id)}</p><p>Belastung: {moodLabel(lastMood(profile.id))}</p></button>)}</section>{child&&<section className="work-card"><h2>{child.displayName} – Fortschritt</h2><ul className="summary-list"><li>Werkelpunkte gesamt: {summary.points}</li><li>Letzte Werkel-Runde: {lastSession ? new Date(lastSession.startedAt).toLocaleString("de-DE") : "noch offen"}</li><li>{summary.started} Aufgaben gestartet</li><li>{summary.completed} abgeschlossen</li><li>{summary.correctSteps} richtige Teilschritte</li><li>{summary.help} Tipps genutzt</li><li>{summary.repairs} Reparaturen geschafft</li><li>Belastung: {moodLabel(summary.mood)}</li></ul><h3>Addition</h3><ul className="summary-list"><li>Einer addieren: {summary.correctSteps > 2 ? "sicher" : summary.help > 0 ? "mit Hilfe" : "üben"}</li><li>Übertrag zu Zehnern: {summary.help > 1 ? "mit Hilfe" : "üben"}</li><li>Zehner mit Übertrag: üben</li><li>mehrere Überträge: noch nicht stabil</li></ul><h3>Punkte-Historie</h3><ul className="summary-list"><li>+{pointsFor("correct_partial_step")} Punkte für Teilschritte</li><li>+{pointsFor("task_completed")} Punkte für abgeschlossene Aufgaben</li><li>+{pointsFor("repair_completed")} Punkte für Reparatur</li><li>+{pointsFor("mood_reported")} Punkte für Belastungsantwort</li><li>+{pointsFor("help_used")} Punkte für sinnvoll genutzte Tipps</li></ul></section>}<section className="work-card"><h2>Letzte Lernereignisse</h2><div className="event-list">{childEvents.slice(0,20).map(event=><article key={event.id} className="event-row"><b>{event.event_type}</b><span>{new Date(event.created_at).toLocaleString("de-DE")}</span><span>{event.task_left !== undefined ? `${event.task_left} + ${event.task_right}` : ""}</span><span>{event.step ?? event.repair_type ?? ""}</span></article>)}</div></section></main>;
  function pointsFor(reason:string){ return childRewards.filter((reward)=>reward.reason===reason).reduce((sum,reward)=>sum+reward.points,0); }
  function lastMood(childId:string){ return events.find((event)=>event.child_profile_id===childId && event.event_type==="session_mood_reported")?.mood; }
  function lastRoundLabel(childId:string){ const session=listLearningSessions().filter((item)=>item.childProfileId===childId).sort((a,b)=>String(b.startedAt).localeCompare(String(a.startedAt)))[0]; return session ? new Date(session.startedAt).toLocaleDateString("de-DE") : "noch keine"; }
}

function moodLabel(mood: string | undefined) { return mood === "easy" ? "🙂 leicht" : mood === "ok" ? "😐 okay" : mood === "hard" ? "🙁 schwer" : mood === "too_much" ? "😣 zu viel" : "noch nicht beantwortet"; }
