"use client";
import { Fragment, useEffect, useState } from "react";
import { useRouter } from "next/navigation";
import { createUser, getCurrentUser, listUsers, logout, updateUser, type UserAccount } from "../../lib/auth";
import { getAllChildren } from "../../lib/learning-events";

export default function AdminPage(){ const router=useRouter(); const [users,setUsers]=useState<UserAccount[]>([]); const [editing,setEditing]=useState<UserAccount|null>(null); const [form,setForm]=useState({displayName:"",email:"",password:""}); const [message,setMessage]=useState("");
  function refresh(){setUsers(listUsers().filter(u=>u.role==="parent"));}
  useEffect(()=>{ const user=getCurrentUser(); if(!user){router.replace("/login"); return;} if(user.role!=="admin"){router.replace("/parent"); return;} refresh();},[router]);
  async function createParent(e:React.FormEvent){e.preventDefault(); setMessage(""); try{await createUser({...form, role:"parent"}); setForm({displayName:"",email:"",password:""}); refresh(); setMessage("Elternprofil wurde angelegt.");}catch{setMessage("Elternprofil konnte nicht angelegt werden.");}}
  async function saveParent(e:React.FormEvent){e.preventDefault(); if(!editing)return; const update: {displayName:string; email:string; isActive:boolean; password?:string} = {displayName:editing.displayName,email:editing.email,isActive:editing.isActive}; if(form.password) update.password=form.password; await updateUser(editing.id, update); setEditing(null); setForm({displayName:"",email:"",password:""}); refresh();}
  const childCounts=new Map<string,number>(); getAllChildren().forEach(c=>childCounts.set(c.parentAccountId,(childCounts.get(c.parentAccountId)??0)+1));
  return <main className="page-shell"><section className="hero compact"><p className="eyebrow">Adminbereich</p><h1>Elternprofile</h1><button className="secondary" onClick={()=>{logout(); router.replace("/login")}}>Abmelden</button></section><section className="work-card"><h2>Elternprofil anlegen</h2><form className="task-form stacked" onSubmit={createParent}><input aria-label="Name" placeholder="Name" value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})} required/><input aria-label="E-Mail" placeholder="E-Mail" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})} required/><input aria-label="Initiales Passwort" placeholder="Initiales Passwort" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})} required/><button>Elternprofil anlegen</button></form>{message&&<p className="gentle-note">{message}</p>}</section><section className="work-card"><h2>Elternliste</h2><div className="admin-table"><b>Name</b><b>E-Mail</b><b>Status</b><b>Anzahl Kinder</b><b>Erstellt am</b><span />{users.map(user=><Fragment key={user.id}><span>{user.displayName}</span><span>{user.email}</span><span>{user.isActive?"aktiv":"inaktiv"}</span><span>{childCounts.get(user.id)??0}</span><span>{new Date(user.createdAt).toLocaleDateString("de-DE")}</span><button onClick={()=>{setEditing(user); setForm({...form,password:""});}}>Bearbeiten</button></Fragment>)}</div></section>{editing&&<section className="work-card"><h2>Elternprofil bearbeiten</h2><form className="task-form stacked" onSubmit={saveParent}><input value={editing.displayName} onChange={e=>setEditing({...editing,displayName:e.target.value})}/><input type="email" value={editing.email} onChange={e=>setEditing({...editing,email:e.target.value})}/><input type="password" placeholder="Neues Passwort (optional)" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><label><input type="checkbox" checked={editing.isActive} onChange={e=>setEditing({...editing,isActive:e.target.checked})}/> aktiv</label><button>Speichern</button></form></section>}</main>}
